//Valori pentru functionare

//DIMENSIUNILE BUFFERULUI DE MESAJE
#define BUFFER_LEN 20
#define BUFFER_WIDTH 10
//LUNGIMEA COMENZII DE DESCHIDERE USA
#define CMD_LEN 3000
//DURATA MAXIMA A UNUI CICLU DE INTRARE
#define CICLE_TIME 15000
//NR. MAXIM DE INCERCARI
#define MAX_TRIES 1
// GREUTATEA MINIMA LA CANTAR
#define MIN_WEIGHT 5*kg
#define TAR_PLUS 12*kg
#define TAR_MINUS 4*kg
// FRECVENTA MESAJELOR DE CANTAR
#define CHECK_MSG_FRQ 30000
#define MIN_TIME_ERR 1
//DURATA COMENZILOR DE IESIRE DE LA FINALUL CICLULUI
#define W8_TIME_LOCK 2000
#define CMD_FOR_LOCK 2000
//DURATA CONFIRMARII CICLULUI CORECT EFECTUAT
#define ACK_LEN 2000
